### ISSUE TITLE
Constrain to grid

### ISSUE THREAD

**Issue by KyleAMathews** [STRML/react-resizable#1]
e.g. every 100px would be very useful.

**Comment by STRML** [comment]
Good suggestion!

You can now pass options directly to the underlying `<Draggable>` instance. See [the example](https://github.com/STRML/react-resizable/blob/master/test/TestLayout.jsx#L18).

This is part of 0.2.0, now available on npm.

All draggable options are available [here](https://github.com/strml/react-draggable).

**Comment by KyleAMathews** [comment]
Haha, fast turnaround :D Thanks!
