### ISSUE TITLE
weird behavior when working with the onResizeStart/Stop props

### ISSUE THREAD

**Issue by rowanG077** [STRML/react-resizable#10]
It seem that there is a weird issue where the resizable doesn't correctly resize when using the `onResizeStart` and `onResizeStop` props. I use the handle and on the drag it immediately changes the div to a height and width that are way too large.

Here is a minimal test case:

```
'use strict';
var React = require('react');
var Resizable = require('react-resizable').Resizable;
require('!style!css!./css/style.css');


var Bugtest = React.createClass({
  getInitialState: function() {
    return {
      width: 300,
      height: 300,
      resizing: false
    };
  },
  onResizeStart: function() {
    this.setState({resizing: true});
  },
  onResizeStop: function() {
    this.setState({resizing: false});
  },
  onResize: function(event, {element, size}) {
    this.setState({width: size.width, height: size.height});
  },
  render: function() {
    return (
      <Resizable height={this.state.height} width={this.state.width} 
        style={{
          width: this.state.width + 'px', 
          height: this.state.height + 'px',
          backgroundColor: "blue",
          position: "absolute"
        }} 
        onResize={this.onResize} 
        onResizeStart={this.onResizeStart} 
        onResizeStop={this.onResizeStop}>
          <div> </div>
      </Resizable>
    )
  }

});

React.render(<Bugtest />, document.getElementById('content'));
```

you have to use the standard css in the package to use this example.

Tested that the same bug occurs in firefox, chrome, opera and internet explorer.

**Comment by rowanG077** [comment]
So with my limited javascript experience I have looked at some of the code and it seems that the problem is in draggable that is a dependancy. 

in the function `handleDragStart` the setstate willl not correctly update the offset. And by that I mean that react `setState()` doesn't seem to work properly...

Below is the function with some log statements to show the issue, `SetState()` is called with the offset values, but when checking the callback of it the values have not changed. I have no idea how to fix this issue. I hope some of you javascript/react gurus can help fix it!

    handleDragStart: function (e) {
      // Make it possible to attach event handlers on top of this one
      this.props.onMouseDown(e);

        // Short circuit if handle or cancel prop was provided and selector doesn't match
        if ((this.props.handle && !matchesSelector(e.target, this.props.handle)) ||
          (this.props.cancel && matchesSelector(e.target, this.props.cancel))) {
          return;
        }

      // Call event handler. If it returns explicit false, cancel.
      var shouldStart = this.props.onStart(e, createUIEvent(this));
      if (shouldStart === false) return;

      var dragPoint = getControlPosition(e);

      // Add a style to the body to disable user-select. This prevents text from
      // being selected all over the page.
      addUserSelectStyles(this);

      var offsetX = dragPoint.clientX - this.state.clientX;
      var offsetY = dragPoint.clientY - this.state.clientY;

      console.log('draggable || handleDragStart dragpoint, Y: ' + dragPoint.clientY + ',X: ' + dragPoint.clientX);
      console.log('draggable || handleDragStart client, Y: ' + this.state.clientY + ',X: ' + this.state.clientX);
      console.log('draggable || handleDragStart offset, Y: ' + offsetY + ',X: ' + offsetX);

      // Initiate dragging. Set the current x and y as offsets
      // so we know how much we've moved during the drag. This allows us
      // to drag elements around even if they have been moved, without issue.
      this.setState({
        dragging: true,
        offsetX: offsetX,
        offsetY: offsetY
      }, function() {
        // Add event handlers
        console.log('draggable || handleDragStart offset AFTER setstate, Y: ' + this.state.offsetY + ',X: ' + this.state.offsetX);
      });
      
      addEvent(document, dragEventFor['move'], this.handleDrag);
      addEvent(document, dragEventFor['end'], this.handleDragEnd);
    },

**Comment by rowanG077** [comment]
the problem is `componentWillReceiveProps` in react-resizable. this function is called everytime a prop changes. this function resets the draggable offsets and current drag positions and also the initialwidth and height of the resizable.
That's the reason why it seemed like `setState` was working, it was simply overwritten.

Removing the function fixes the issue, I don't see why you would reset the entire offsets if a prop changes (which happens everytime you start dragging). Removing the functions fixes everything. I have issued a pull request but I might me missing the reason why this was implemented in the first place.

**Comment by STRML** [comment]
Thanks @rowanG077 , sorry for not getting back to you sooner. I am working to finish a rewrite of `<Draggable>` that exposes a new interface, `<DraggableCore>`, which manages no internal state. It is far better for library use as direct manipulation of the draggable is far easier.

Once that is done, a lot of these more terrible hacks can be removed and the bug will be fixed.

https://github.com/mzabriskie/react-draggable/tree/coreRefactor

**Comment by 9o** [comment]
What's the status on this?
