### ISSUE TITLE
Preview of the resize

### ISSUE THREAD

**Issue by ayozebarrera** [STRML/react-resizable#12]
I'm developing a desktop on a webapp and your components works well.

But, in one of the window of my app, I have a lot of icons (like 300) and when I resize the perfomance isn't good..

So, as suggestion, I'll consider a way to do the resize with a preview (imagine just a div transparent on the top of the window, absoluted, updating the props with state) and on the onResizeStop we could update the window.

Hope I explained.
Tell me what do you think about this.

See ya.

**Comment by rowanG077** [comment]
You can implement this alongside resizable without needing to add additional code to it. Just use onResizeStart and onResizeStop

**Comment by ayozebarrera** [comment]
Oh right, my mistake!
