### ISSUE TITLE
[Bug] Input element loses the ability to enter text after removing <Resize />

### ISSUE THREAD

**Issue by eavam** [STRML/react-resizable#120]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [x] Bug
- [ ] Feature Request
- [ ] Question

### Problem Report

Hello.
I caught an interesting bug. After I remove one <Resize /> component, the input element loses the ability to enter text, but does not lose focus.

![](https://media.giphy.com/media/Uq5a7Zr56SKSc5VJrn/giphy.gif)

#### System Info

Node Version: 12.13.0
Browser: Chrome 79.0.3945.130 
OS: MacOS 10.15.2

#### Reproduction

[Demo](https://codesandbox.io/s/resizable-bug-g0k2w?fontsize=14&hidenavigation=1&theme=dark)

**Comment by front-thinking** [comment]
got the same bug, the input lose the ability to input text without losing focus status, have to click the input again before continue to input text.

**Comment by front-thinking** [comment]
> ### Thanks for opening an issue!
> Please select the type of issue you're reporting. For questions.
> 
> * [x]  Bug
> * [ ]  Feature Request
> * [ ]  Question
> 
> ### Problem Report
> Hello.
> I caught an interesting bug. After I remove one component, the input element loses the ability to enter text, but does not lose focus.
> 
> ![](https://camo.githubusercontent.com/f9e2bab63cf0714e998ecf398adfcb2806f8d065/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f55713561375a723536534b536335564a726e2f67697068792e676966)
> 
> #### System Info
> Node Version: 12.13.0
> Browser: Chrome 79.0.3945.130
> OS: MacOS 10.15.2
> 
> #### Reproduction
> [Demo](https://codesandbox.io/s/resizable-bug-g0k2w?fontsize=14&hidenavigation=1&theme=dark)

you got any solution?

**Comment by eavam** [comment]
I checked, and this bug is no longer reproducible.
