### ISSUE TITLE
Support to add custom props to Resizable and ResizableBox

### ISSUE THREAD

**Issue by charanjit-singh** [STRML/react-resizable#127]
Please select the type of issue you're reporting. For questions.

- [ ] Bug
- [x] Feature Request
- [ ] Question

I'm speaking for those developers out there, who have to integrate these components in other libraries like SlateJs, etc. So in order to do that, those developers have to add custom props like: 'data-slate-node' but there's no internal support for such functionality.

It could be like: 
`<Resizable ...props extraProps={extraProps} />`, that's a design decision, but yeah, this is one of the required feature that developers out there are looking for.

**Comment by devinhalladay** [comment]
+1, this library could be very strong with a little extra love! I'm not sure I'll have time to write a PR any time soon but wanted to voice support for this feature

**Comment by STRML** [comment]
I don't understand this issue description. But if it really is so easy as you say, it would be trivial to create a PR.

This is open source, not a for-profit product. I released it because I built it for my own projects and I thought it would be useful to others. That's it.

**Comment by devinhalladay** [comment]
jeez lol
