### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by jbe456** [STRML/react-resizable#13]
Under IE11, it throws an exception at the line `27158` of `bundle.js` because touches is `undefined`:

```
	  var position = !isTouchDevice ? e : e.touches[0];
```

The problem comes from the fact `isTouchDevice` is `true` although I'm not on a touch device. Turning it to `false` makes everything working fine. I suggest improving the following piece of code using `navigator.msMaxTouchPoints`:

```
	    var isTouchDevice = (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0));
```

See latest update on http://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript

**Comment by STRML** [comment]
Fixed in 1.0.
