### ISSUE TITLE
Question - Module error when building on Travis CI

### ISSUE THREAD

**Issue by vamshikrishnanethi** [STRML/react-resizable#130]
Hello,

I am running into a Module parse failed error when trying to deploy the application using Travis CI. All my builds were working fine till yesterday and started failing from today. 

I am able to run the application fine from my local but its erroring out on Travis. I did check with the Travis team to make sure they have not made any updates which causes this error and they did not make any updates.

PFA a screenshot of the build error from Travis CI

![image (12)](https://user-images.githubusercontent.com/17882168/81747550-48674280-9476-11ea-9a35-c22e26c70792.png)

Node Version is 8.17.0 and npm version is 6.13.4

Any help is appreciated. Thanks!

**Comment by STRML** [comment]
Hi - sorry about this, this is a known issue in the sub-dependency, `react-draggable`: https://github.com/STRML/react-draggable/issues/479

It is fixed in the latest release, `4.4.1`. An easy way to upgrade is to simply remove react-resizable from your project, and re-add it.
