### ISSUE TITLE
React resizable doesn't work with react-draggable anymore

### ISSUE THREAD

**Issue by mmesar** [STRML/react-resizable#143]
Please select the type of issue you're reporting. For questions.
- [x] Bug
- [ ] Feature Request
- [ ] Question

With new version (v2.0.0) nesting react-resizable within react-draggable is not working.

#### System Info

Node Version: v12.18.2
Browser: Chrome
OS: Windows 10

project created with react scripts / create react app
using: 
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-draggable": "^4.4.3",
    "react-resizable": "^2.0.0",
    "react-scripts": "3.4.3"

#### Reproduction
https://codesandbox.io/s/red-fog-umlic?file=/src/App.js - this one doesnt work
https://codesandbox.io/s/condescending-feynman-t75eq?file=/src/App.js - this one works but has react resizable v1.10.1

**Comment by MadSummer** [comment]
use ResizableBox instead of Resizable and works fine

**Comment by mmesar** [comment]
I didn't try. I believe you. I don't think it is the right solution, and I didn't see anywhere in documentation explicit statement that we should replace Resizable with ResizableBox when updating from an old version to new.

**Comment by STRML** [comment]
This is why the deprecation message exists on 2.0.0 - we removed props passthrough and this turned out to break too many apps. This is outlined in detail in the [CHANGELOG](https://github.com/STRML/react-resizable/blob/master/CHANGELOG.md).

**Comment by lili21** [comment]
https://codesandbox.io/s/admiring-hopper-wji3n?file=/src/App.js

It does work as expected. If the resize direction is one of `n`, `nw`, `ne`, `w`, `sw`, `nw`
