### ISSUE TITLE
Resizable and Draggable

### ISSUE THREAD

**Issue by andrewgleave** [STRML/react-resizable#2]
Is it possible to have an element be resizable and generally resizable as well? i.e the width and height can be changed as in the demo, but the element also dragged around? 

```javascript
<ResizableBox
  className={ this.props.className }
  draggableOpts={{
    start: { x: this.props.frame.x, y: this.props.frame.y },

    grid: [25, 25],
    onStop: this.handleDragStop
  }}
  width={ this.props.frame.w }
  height={ this.props.frame.h === 'auto' ? 100 : this.props.frame.h }
  minConstraints={[100, 100]}>
    <span>Some markup</span>
</ResizableBox>
```

**Comment by STRML** [comment]
Yes, this is possible. 

The boxes in the [react-grid-layout showcase](https://strml.github.io/react-grid-layout/examples/0-showcase.html) are resizable and draggable. This is done by simply nesting the two. See [the source](https://github.com/STRML/react-grid-layout/blob/a9c78499f6cb39b1339efed91bd239e9956f41d2/lib/GridItem.jsx#L302) for how this is done.

**Comment by andrewgleave** [comment]
Ok thanks for the pointer.
