### ISSUE TITLE
Touch screen laptop chrome Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mitermayer** [STRML/react-resizable#21]
When attempting to resize on the demo page with chrome browser on a laptop that has support for touch screen i get the following error:

I get the error 

**Uncaught TypeError: Cannot read property '0' of undefined**

```
function getControlPosition(e) {
	  var position = !isTouchDevice ? e : e.touches[0];
	  return {
	    clientX: position.clientX,
	    clientY: position.clientY
	  }
}
```

**Comment by STRML** [comment]
Fixed in 1.0
