### ISSUE TITLE
Demo is broken in chrome

### ISSUE THREAD

**Issue by mathisonian** [STRML/react-resizable#31]
currently going to https://strml.github.io/react-resizable/examples/1.html yields a page that looks like this
![screen shot 2016-04-08 at 2 57 29 pm](https://cloud.githubusercontent.com/assets/1074773/14394436/469f1328-fd9a-11e5-98df-d08ddb95965d.png)

with the following error message 

```
Uncaught TypeError: Cannot read property 'Component' of undefined
```

on line 1602 of bundle.js

**Comment by STRML** [comment]
Working now, thanks. It appears a minor webpack version upgrade introduced an incompatibility - [parameterized externals](https://github.com/webpack/webpack/blob/master/examples/externals/webpack.config.js#L8) now silently fail (webpack writes `module.exports = undefined`) unless the build is configured with `libraryTarget: 'umd'`.
