### ISSUE TITLE
Width and Height are now opaque

### ISSUE THREAD

**Issue by queimadus** [STRML/react-resizable#33]
Since 5da49c6 `width` and `height` is not passed to the component's children.

I previously used these properties to debounce an heavy operation inside the container and performed some extra transformations as well.

Are you committed to not leaking these properties and only exposing the `style` with the computed strings?

**Comment by STRML** [comment]
Yes, that's intentional - I'm sorry that this was a breaking change for you. Leaking these properties was not intentional and caused additional, unnecessary DOM writes.

**Comment by queimadus** [comment]
Ok thanks. I'll rely on the `style` properties for the debouncing.
