### ISSUE TITLE
resizing elements on left border causes random jumping

### ISSUE THREAD

**Issue by arekkas** [STRML/react-resizable#38]
I have a resizable div which is `float: right`. The handler is on the left side. Everything works fine when the handler is on the right side but I'm having some troubles with the one on the right.

The following gif shows two screens. One, where the resizable is floating left and one where it's floating right. The floating left example is included to show you that it generally works.

![jumpingstuff](https://cloud.githubusercontent.com/assets/3372410/16547753/df06c1da-4177-11e6-9362-de081b281946.gif)

After some debugging and seeing that it works fine if I scale the **inner** element only, I believe that the issue is caused because the origin of the element wrapping resizeable (which is top left I guess?) changes:

![jumpingstuff3](https://cloud.githubusercontent.com/assets/3372410/16547764/0fb3f410-4178-11e6-823e-d555407821ae.gif)

In pseudocode, the react structure of the borken example is:

```jsx
<div width="123px" float="right">
  <ReactResizable>
      <children />
  </ReactResizable>
</div>
```

The react structure of the example without jumping is:

```jsx
<div float="right">
  <ReactResizable>
    <div width="123px">
      <children />
    </div>
  </ReactResizable>
</div>
```

The cause for the jumping is that in `onResize(event, { size }) { console.log(size) }`, `size.width` fires random widths, as seen in the console:

![jumpingstuff4](https://cloud.githubusercontent.com/assets/3372410/16547803/4d4b518c-4179-11e6-9ac5-355f7ea2c47a.PNG)

So - how is it possible to resize an element to the right?

**Comment by arekkas** [comment]
From looking at the code, this might be caused by the slack state?

**Comment by arekkas** [comment]
`deltaY` in [`resizeHandler`](
https://github.com/STRML/react-resizable/blob/master/lib/Resizable.jsx#L135) is jumping around between negative and positive values when the issue occurs:

![deltajumper](https://cloud.githubusercontent.com/assets/3372410/16556980/6c8c8638-41dd-11e6-80d0-b1b1a4493879.PNG)

This does not happen when dragging an object on the right side, which is working fine:

![delta2](https://cloud.githubusercontent.com/assets/3372410/16557037/bad373ba-41dd-11e6-8397-ee7f41e21489.PNG)

**Comment by arekkas** [comment]
upstream https://github.com/mzabriskie/react-draggable/issues/170

**Comment by arekkas** [comment]
when `min/maxConstraints` isn't set, the flickering occurs. When min/max is set, `size.width` is always 0 in `onResize(event, { size })`

**Comment by arekkas** [comment]
This will be resolved once https://github.com/mzabriskie/react-draggable sees it's 2.1.3 release :)

**Comment by AnandMathew** [comment]
hey @aeneasr, when the div is floated right (the resizing handle bar is on the left) and you drag the handle to the left, does the div increase in the left or right side? 
Seems to me that in the first gif, the div increases in the same direction that you are pulling, while in the second gif, the div increases in the opposite direction that you are pulling!

Also, did you use css to shift the handlebar from the right side to the left side?

**Comment by PovarovDenis** [comment]
For those who has same problem:
add `draggableOpts={{offsetParent: document.body}}` to ResizableBox
Good luck :+1:

**Comment by msueping** [comment]
I'm having the random jumping issue too on a div where the resize handle is on the right (and is the only one). I've also noticed that it only happens when I have the className="box" applied to the <ResizableBox>. Without that class there's no problems but I need it in order to use the CSS that hides the handles until the element is hovered over.

Using the suggestion above about adding a draggableOpts={{offsetParent: document.body}} to the ResizableBox solved the random jumping troubles. THANKS @PovarovDenis
