### ISSUE TITLE
ResizeableBox onResize event

### ISSUE THREAD

**Issue by robzolkos** [STRML/react-resizable#4]
I'm trying to handle the onResize event in a ResizableBox

I have it defined like

`<ResizableBox onResize={this.resizeHandler} ...`

And a function called resizeHandler()

But the event isn't firing.  Do I need to handle the events some other way?  I couldn't see an example in the tests/docs.

**Comment by ayozebarrera** [comment]
How you did that @robzolkos, I'm having the same issue
