### ISSUE TITLE
onResizeStart event object is invalid

### ISSUE THREAD

**Issue by JoaoMosmann** [STRML/react-resizable#45]
When I try to use the event object on onResizeStart, it throws the following warning 

```
warning.js:19 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `preventDefault` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```

For some reason, the onResizeStart event is a Proxy Event object. So it must be persisted to avoid this kind of problem.

**Comment by STRML** [comment]
Yet, we're not using `preventDefault` anywhere. Going to hold off on #46 until I figure out what is doing this.

Could you get something reproducible at http://www.webpackbin.com/?

**Comment by STRML** [comment]
I've put together a boilerplate that should help: http://www.webpackbin.com/41YFBvekG

**Comment by JoaoMosmann** [comment]
http://www.webpackbin.com/Vk2OEOeyG

In the console, you can see that the **onResizeStart** event is different from the event of **onResize** and **onResizeStop**. The onResizeStart event is a **SyntheticMouseEvent**, while the others are a normal **MouseEvent**.

In this example the error is not occurring. But you can see the event objects divergence.

In my project I'm using **react-resizable** alongside **react-dnd** to manage the drag n' drop. I believe the error is caused by this combination.

However, I need to do a preventDefault on the **onResizeStart** to prevent that the element won't be dragged instead of dragged.

If you think it's necessary to reproduce the actual error. I can do it, but i'll take a little longer.

**Comment by STRML** [comment]
In that case, when you intercept the method, you should persist it yourself. A change to the library should not be made.

**Comment by JoaoMosmann** [comment]
I did this. But in the moment that I get the event object, it's already nullified. Probably because of a conflict with **react-dnd**. 

I digged into the code and the problem comes from the dependency **react-draggable**

The events listeners for **onResize** and **onResizeStop** are added directly to the **document** dom object.
https://github.com/mzabriskie/react-draggable/blob/master/lib/DraggableCore.es6#L250-L251

But the **onResizeStart** uses the event object from a mouseDown, which is attached through reacts virtual dom
https://github.com/mzabriskie/react-draggable/blob/master/lib/DraggableCore.es6#L330

That explains why the difference.

Another solution could be changing this following line on **react-draggable**
https://github.com/mzabriskie/react-draggable/blob/master/lib/DraggableCore.es6#L230

to 

```ts
const shouldUpdate = this.props.onStart(e.nativeEvent, coreEvent);
```

However, I'm sure about the possible side-effects of this change. The `e.persist()` on **Resizable** component would be much safer.

**Comment by missing1984** [comment]
Any update on this? ran into similar issues

**Comment by missing1984** [comment]
Take a closer look at this. It should caused by the following code 
https://github.com/STRML/react-resizable/blob/master/lib/Resizable.jsx#L159
```
this.setState(newState, () => {
   this.props[handlerName] && this.props[handlerName](e, {node, size: {width, height}});
});
```
The callback runs asynchronously and therefore nullified the event (https://facebook.github.io/react/docs/events.html)

There should be 2 approach to fix this.
1.  Persistent the event by calling e.persist();
2. Invoke callback synchronously, something like
```
this.setState(newState);
this.props[handlerName] && this.props[handlerName](e, {node, size: {width, height}});
```
@STRML Thoughts?

**Comment by STRML** [comment]
I agree - I can't recall why I made it async. I believe I just wanted the change to actually be in the DOM when you get the callback.

I'll adjust in a way that doesn't break existing behavior.
