### ISSUE TITLE
LICENSE available?

### ISSUE THREAD

**Issue by tim-buendorf** [STRML/react-resizable#48]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [ X] Question

### Problem Report

> Is there a LICENSE available - similar to react-grid-layout? I need to be able to take a screenshot of the repository showing LICENSE in the file list. Thanks. Or, since I am using react-grid-layout, does having that license cover react-resizable?

**Comment by STRML** [comment]
The license is available in the [package.json](https://github.com/STRML/react-resizable/blob/master/package.json#L28), as it is in many npm repos.
