### ISSUE TITLE
How to specify Resizable component on onResize function ?

### ISSUE THREAD

**Issue by yayoc** [STRML/react-resizable#50]
- [ ] Bug
- [ ] Feture Request
- [x] Question

### Problem Report

Hi,
I am beginner for `React` though,
I would like to know how to specify the object which is resizing on `onResize function`
when the `React.Component` has multiple `Resizable` components.

`onResize` handler seems pass `event, node and size` as arguments in the current implementation,
however, I could not specify the object which is resizing on `onResize handler`.

To solve this problem, I forked this repo then add new commit on my side.

https://github.com/yayoc/react-resizable/commit/52405a536e7c2f0e0fb6962fbba7915900d4e13c

I'm not sure this implementation is a better way.
Please let me know what your idea about this.

If this commit is satisfied your idea, I will create PR.

Thanks.

**Comment by STRML** [comment]
Hi - no, you want to do something like this:

```js

onResize(id, event, node, size) {
  // ...
}

render() {
  return (
    <div>
      <Resizable onResize={this.onResize.bind(this, 1)} ... />
      <Resizable onResize={this.onResize.bind(this, 2)} ... />
    </div>
  );
}
```

**Comment by yayoc** [comment]
@STRML Thanks!
