### ISSUE TITLE
Deprecated PropTypes reference - needs to use prop-types package

### ISSUE THREAD

**Issue by inverts** [STRML/react-resizable#54]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [x] Bug
- [ ] Feature Request
- [ ] Question

### Problem Report
Looks like we've got the same PropType deprecation update to make here, noticed I still was getting the warnings because react-grid-layout depends on react-resizable and react-draggable. Won't have time to make a pull request for this one today.
(see https://github.com/STRML/react-grid-layout/issues/538)

**Comment by Scimonster** [comment]
This should be closed as it was fixed
