### ISSUE TITLE
Readme Links Not Working

### ISSUE THREAD

**Issue by kevinahuber** [STRML/react-resizable#58]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [x ] Bug
- [ ] Feature Request
- [ ] Question

### Problem Report

> The readme links do not work, because they reference a jsx file, which was probably switched to js without updating the links.

#### System Info

N/A

#### Reproduction

Click on the example links in the readme

**Comment by STRML** [comment]
Fixed
