### ISSUE TITLE
Remove required "width" prop

### ISSUE THREAD

**Issue by benhowdle89** [STRML/react-resizable#6]
I'm intentionally not setting a `width` prop and receiving (understandably) the warning:

`Warning: Failed propType: Required prop`width`was not specified in`Resizable`. Check the render method of`ResizableBox`.`. My use-case is that I only want something vertically resizable so I need the width of the element to span the width of the parent, ie. 100%, so I don't really want/need to pass a width.

**Comment by TheTourer** [comment]
I am having this problem too, but the opposite: I want a ResizableBox to resize horizontally only, and to take its initial height and width from the CSS associated with the class on the element in question.

Is there a way to do this?

**Comment by STRML** [comment]
We'd have to add an option for setting resizable directions ('horizontal', 'vertical', default 'both'). Happy to accept a PR. I believe it would be prudent to update the propTypes check then to read this direction param so it can validate or ignore width/height properly.

**Comment by TheTourer** [comment]
I can certainly look into making that change. My use case for this component is pretty complicated though, so I want to make sure I have a chance of using this as desired given the change(s):

I have a button that, `onClick`, expands into a full panel with a dynamic height based on its content (using flexbox) by adding an `open` class, which also animates the transition. I want this panel in its open state to be resizable horizontally, without affect the closed state and closing/opening animation.

The initial size of the `ResizableBox` should be as calculated by CSS.

Do you think that's feasible?

**Comment by STRML** [comment]
So it opens vertically (but is static horizontally), and once it's at
full height, is resizable horizontally? I think that's fine.

The limitation is that Resizable needs to know its own size in any axis
that it moves. Otherwise, it doesn't know what CSS to set.

**Comment by Anima-t3d** [comment]
There is a working PR for this: https://github.com/STRML/react-resizable/pull/40

**Comment by micaste** [comment]
The PR #40 aims at restricting the direction of dragging. It helps with the initial issue from @benhowdle89, but to my mind it is not enough since he would still have a warning from React from not specifying the width prop.

Once #40 is merged, I could make a PR to change the propTypes and only require width/height when it is relevant, meaning if changes are allowed by dragging in that direction.
This would allow to set a static width/height using css or inline styling.

**Comment by STRML** [comment]
e90184ec1231978827433b2e60bc17919104017b, will be in `1.6.0`.

**Comment by armedi** [comment]
Hi [benhowdle89](https://github.com/benhowdle89), is your issue solved? If so, how do you manage to get rid of the error message?

I still experience this exact same issue now.
