### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by yxliang01** [STRML/react-resizable#62]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [X] Bug
- [ ] Feature Request
- [ ] Question

### Problem Report

The demo doesn't work. Browser console gives me the following message.
```
Error: Module build failed: ReferenceError: Unknown plugin "transform-flow-comments" specified...
```

#### System Info

Browser: Firefox and Chrome
OS: Win 10

#### Reproduction

Just go to the demo page at https://strml.github.io/react-resizable/examples/1.html

**Comment by STRML** [comment]
Thanks, ran a rebuild and this is fixed.
