### ISSUE TITLE
100% or full width

### ISSUE THREAD

**Issue by tsnevillecom** [STRML/react-resizable#66]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [ ] Bug
- [x] Feature Request
- [ ] Question

### Problem Report

> Would love a 100% width option. I want my box to start at the full width of the screen.

#### System Info

Node Version: 6.5.0
Browser: Chrome
OS: macOS 10.12.4

#### Reproduction

If this is a bug report, please provide a reproduction of the issue by going to
http://www.webpackbin.com/41YFBvekG.
Paste a link here to your working reproduction.

**Comment by STRML** [comment]
You are free to style the resizable box however you like. Use CSS.

**Comment by tsnevillecom** [comment]
I have to provide a width in the component, or I'll get an error "The prop `width` is marked as required in `Resizable`, but its value is `undefined`." Unless you have another idea, I'd like to see an example of what CSS handling this.

**Comment by AlecRust** [comment]
More at: https://github.com/STRML/react-resizable/issues/69
