### ISSUE TITLE
ResizableBox onResize

### ISSUE THREAD

**Issue by ayozebarrera** [STRML/react-resizable#7]
I can't get the event firing... how works this?

```js
<ResizableBox height={300} width={350} onResize={this.resize}>
  {content}
</ResizableBox>
```

my function resize() should log in the console.. but never gets fired

**Comment by STRML** [comment]
Sorry, this is a documentation issue. You should be using `<Resizable>`, not `<ResizableBox>`. See the source and I'll update the README shortly.

**Comment by ayozebarrera** [comment]
Yeah I already noticed that. Thanks :)
