### ISSUE TITLE
onResize is not getting the element being resized.

### ISSUE THREAD

**Issue by harivasista** [STRML/react-resizable#72]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [x] Question

### Problem Report

I am using the component to resize three different divs in the same page. How do I get to know which Resizable element is being resized. 

onResize(event,{element, size})
The element variable in this callBack is undefined.

#### System Info

Node Version: 6.5.0
Browser: working with electron app
OS: Win 10

**Comment by STRML** [comment]
That's odd. Perhaps you can debug and figure out why element is not defined.

You should be able to still get the DOM element through the event.

Harish Kumar wrote:

**Comment by AjaxJackjia** [comment]
change `onResize(event,{element, size}) `  to `onResize(event,{node, size}) `
This is work for me, hope this will work out for your problem.
