### ISSUE TITLE
PR: horizontal and vertical resize handler supported

### ISSUE THREAD

**Issue by RaoHai** [STRML/react-resizable#75]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [ ] Bug
- [x] Feature Request
- [ ] Question

### Problem Report

- For more friendly interactions, offer horizontal and vertical resize handlers.
- `ResizeCallbackData` add an extra param axis, shows which direction that user now resize in.
- ```jsx
     <ResizableBox onResize={(event, { element, size, axis}) => {...}} />
   ```
> ![screen shot 2017-09-11 at 9 53 18 am](https://user-images.githubusercontent.com/566097/30255580-6829122c-966a-11e7-9ea9-7be141ed711e.png)

**Comment by brspurri** [comment]
I would love to see this merged.

**Comment by davvit** [comment]
Is there a way to get this implementation?

**Comment by STRML** [comment]
In #101
