### ISSUE TITLE
Need to remove setting image via a css background image property

### ISSUE THREAD

**Issue by ajaysikdar** [STRML/react-resizable#97]
Issue description
The CSS background-image property should not be used for adding images to page content because it does not provide any reference to the image in the HTML code, and it is not possible to associate text alternatives with the image. Any images that convey important information will not be read by assistive technologies.

Rationale
Text alternatives are critical for people who cannot see images, especially those images that convey important information.

This module is our internal dependency in many places and we are not able to change it.

The issue is in below CSS-

.react-resizable-handle {
  position: absolute;
  width: 20px;
  height: 20px;
  bottom: 0;
  right: 0;
  background: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2IDYiIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiNmZmZmZmYwMCIgeD0iMHB4IiB5PSIwcHgiIHdpZHRoPSI2cHgiIGhlaWdodD0iNnB4Ij48ZyBvcGFjaXR5PSIwLjMwMiI+PHBhdGggZD0iTSA2IDYgTCAwIDYgTCAwIDQuMiBMIDQgNC4yIEwgNC4yIDQuMiBMIDQuMiAwIEwgNiAwIEwgNiA2IEwgNiA2IFoiIGZpbGw9IiMwMDAwMDAiLz48L2c+PC9zdmc+');
  background-position: bottom right;
  padding: 0 3px 3px 0;
  background-repeat: no-repeat;
  background-origin: content-box;
  box-sizing: border-box;
  cursor: se-resize;
}

**Comment by RoccoC** [comment]
Why not use the `handle` prop to render a custom resize handle? This way you can use whatever markup/style fits your needs.

**Comment by ajaysikdar** [comment]
Thanks @RoccoC , we will try that.
