### ISSUE TITLE
Example page fails

### ISSUE THREAD

**Issue by josephmisiti** [STRML/react-resizable#98]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [x] Bug
- [ ] Feature Request
- [ ] Question

### Problem Report

When I go to the example page, I see the following:

![Uploading Screen Shot 2019-03-05 at 12.49.12 PM.png…]()

#### System Info

Browser: Version 71.0.3578.98 (Official Build) (64-bit)
OS: OSX

#### Reproduction

If this is a bug report, please provide a reproduction of the issue by going to
http://www.webpackbin.com/41YFBvekG.
Paste a link here to your working reproduction.

**Comment by josephmisiti** [comment]
<img width="739" alt="screen shot 2019-03-05 at 12 49 12 pm" src="https://user-images.githubusercontent.com/246302/53825866-4ede5e00-3f45-11e9-8ff7-7017437e97e8.png">

**Comment by STRML** [comment]
I can't reproduce this, unless you're talking about the issue template link, which I've replaced to codesandbox in 4ce15ee.
